M_13_IntroductionToDjangoRESTFramework/mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,

    MyLogoutView,
    AboutMeView,
    UserDetailsView,
    UpdateProfileImage,
    UsersListView,
    UpdateAboutMeView,
    RegisterView,
    FooBarView,
    HelloView,
)

app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path('hello/', HelloView.as_view(), name='hello'),
    # path("logout/", logout_view, name="logout"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),

    path('users/', UsersListView.as_view(), name="users"),
    path('users/<int:pk>/', UserDetailsView.as_view(), name="user_me"),
    path('users/<int:pk>/update/', UpdateProfileImage.as_view(), name="update_img"),
    path("about-me/", AboutMeView.as_view(), name="about_me"),
    path("about-me/<int:pk>/update", UpdateAboutMeView.as_view(), name="user_update"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

M_13_IntroductionToDjangoRESTFramework/mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('api/', include('myapiapp.urls'))
]

# urlpatterns += i18n_patterns(
#     path('admin/', admin.site.urls),
#     path('shop/', include('shopapp.urls')),
#     path('myauth/', include('myauth.urls')),
# )

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

M_13_IntroductionToDjangoRESTFramework/mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    ProductDetailsView,
    ProductsListView,
    OrderCreateView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    ProductViewSet,
    OrderViewSet,
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register('products', ProductViewSet)
routers.register('orders', OrderViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path('api/', include(routers.urls)),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
]

M_13_IntroductionToDjangoRESTFramework/mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def profile_avatar_directory_field(instance: 'Profile', filename: str) -> str:
    return 'users/user_{name}/avatar/{filename}'.format(
        name=instance.user.username,
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=profile_avatar_directory_field)

M_13_IntroductionToDjangoRESTFramework/mysite/myauth/forms.py
from django import forms

from myauth.models import Profile


class ImageForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = 'avatar',

M_13_IntroductionToDjangoRESTFramework/mysite/myauth/views.py
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy, reverse
from django.views import View
from django.utils.translation import gettext_lazy, ngettext

from django.views.generic import ListView

from django.views.generic import TemplateView, CreateView, UpdateView, DetailView

from .forms import ImageForm
from .models import Profile


class HelloView(View):
    welcome_message = gettext_lazy('welcome hello world!')

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get('items') or 0
        items = int(items_str)
        products_line = ngettext(
            'one product',
            '{count} products',
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f'<h1>{self.welcome_message}</h1>'
            f'<h2>{products_line}</h2>',
        )


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class UserDetailsView(DetailView):
    template_name = 'myauth/user-me.html'
    model = Profile


class UpdateProfileImage(UserPassesTestMixin, UpdateView):
    def test_func(self):
        if self.request.user.is_staff:
            return True
        if self.request.user == self.get_object().user:
            return True

    model = Profile
    template_name = 'myauth/img-update.html'
    form_class = ImageForm

    def get_success_url(self):
        return reverse(
            'myauth:user_me',
            kwargs={'pk': self.object.pk}
        )

    # def form_valid(self, form):
    #     response = super().form_valid(form)
    #


class UpdateAboutMeView(UpdateView):
    model = Profile
    fields = 'bio', 'agreement_accepted', 'avatar'
    template_name = 'myauth/about-me-update.html'

    def get_success_url(self):
        return reverse(
            'myauth:about_me'
        )


class UsersListView(ListView):
    template_name = 'myauth/users-list.html'
    context_object_name = 'users'
    queryset = User.objects.all()


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})

M_13_IntroductionToDjangoRESTFramework/mysite/myauth/templates/myauth/about-me-update.html
{% extends 'myauth/base.html' %}

{% block title %}
  Update About me
{% endblock %}


{% block body %}
    <h1>Update About me</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'myauth:about_me' %}">Back to user page</a>
    </div>
{% endblock %}

M_13_IntroductionToDjangoRESTFramework/mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
  About me
{% endblock %}


{% block body %}
  <h1>User info</h1>
  {% if user.is_authenticated %}
    <h2>Detail</h2>
    <p>Username: {{ user.username }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Bio: {{ user.profile.bio }}</p>
    <br>
    <div>
    <h3>Avatar</h3>
    {% if user.profile.avatar %}
        <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
    {% else %}
        <div>No avatar yet!</div>
    {% endif %}
    </div>
    <br>
    <div>
        <a href="{% url 'myauth:user_update' pk=user.pk %}">Update yourself info</a>
    </div>
  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
{% endblock %}

M_13_IntroductionToDjangoRESTFramework/mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
      {% endblock %}
    </title>
</head>
<body>
    {% block body %}
    {% endblock %}
<div>
    <a href="{% url 'shopapp:index' %}">Enter to shop</a>
</div>
<div>
    <a href="{% url 'myauth:users' %}">Users list</a>
</div>
<div>
    <a href="{% url 'myauth:about_me' %}">Personal account</a> <b>|</b>
    <a href="{% url 'myauth:logout' %}">Logout</a>
</div>
</body>
</html>

M_13_IntroductionToDjangoRESTFramework/mysite/myauth/templates/myauth/img-update.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update image
{% endblock %}

{% block body %}
    <h1>Update image</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Upload image</button>
        </form>
    </div>
    <div>
        <a href="{% url 'myauth:user_me' pk=object.pk %}">Back to user page</a>
    </div>
{% endblock %}

M_13_IntroductionToDjangoRESTFramework/mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block body %}

  <form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Login</button>
  </form>
{% endblock %}

M_13_IntroductionToDjangoRESTFramework/mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
  Register
{% endblock %}

{% block body %}
  <h1>Register</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
  </form>
{% endblock %}

M_13_IntroductionToDjangoRESTFramework/mysite/myauth/templates/myauth/user-me.html
{% extends 'myauth/base.html' %}

{% block title %}
    User {{ user.name }}
{% endblock %}

{% block body %}
    <h1>User <strong>{{ object.user.name }}</strong></h1>
    <p>Username: {{ object.user.username }}</p>
    <p>First name: {{ object.user.first_name }}</p>
    <p>Last name: {{ object.user.last_name }}</p>
    <p>Bio: {{ object.user.profile.bio }}</p>
    <br>
    <div>
    <h3>Avatar</h3>
    {% if object.user.profile.avatar %}
        <img src="{{ object.user.profile.avatar.url }}" alt="{{ object.user.profile.avatar.name }}">
    {% else %}
        <div>No avatar yet!</div>
    {% endif %}
    </div>

    {% if request.user.is_staff == True or request.user == object.user %}
        <a href="{% url 'myauth:update_img' pk=object.pk %}">Update image</a>
    {% endif %}
{% endblock %}

M_13_IntroductionToDjangoRESTFramework/mysite/myauth/templates/myauth/users-list.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update users
{% endblock %}

{% block body %}

    <h1>Users:</h1>
    {% if users %}
        {% for user in users %}
            <div>
                <p><a href="{% url 'myauth:user_me' pk=user.pk %}">Username: {{ user.username }}</a></p>
                <p>
                    <div>Firstname: {{ user.first_name }}</div>
                    <div>Lastname: {{ user.last_name }}</div>
                <div>
                    {% if user.profile.avatar %}
                        <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
                    {% else %}
                       <div>No avatar yet!</div>
                    {% endif %}
                </div>
        {% endfor %}

    {% else %}
        <div>No user create yet</div>
    {% endif %}

{% endblock %}