M_10_Testing/mysite/shopapp/urls.py
from django.urls import path

from .views import (
    shop_index,
    groups_list,

    ProductsListView,
    ProductDetailsView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,

    OrdersListView,
    OrderDetailsView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    ProductsExportView,
    OrdersExportView,
    )

app_name = "shopapp"

urlpatterns = [
    path("", shop_index, name="index"),
    path("groups/", groups_list, name="groups_list"),

    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/export/", ProductsExportView.as_view(), name="products-export"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),


    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/export/", OrdersExportView.as_view(), name="orders-export"),
    path("orders/<int:pk>/", OrderDetailsView.as_view(), name="order_details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
]

M_10_Testing/mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    class Meta:
        ordering = ["name", "price"]

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")

M_10_Testing/mysite/shopapp/views.py
from timeit import default_timer

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from django.views import View

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Product, Order


def shop_index(request: HttpRequest):
    products = [
        ('Laptop', 1999),
        ('Desktop', 2999),
        ('Smartphone', 999),
    ]
    context = {
        "time_running": default_timer(),
        "products": products,
    }
    return render(request, 'shopapp/shop-index.html', context=context)


def groups_list(request: HttpRequest):
    context = {
        "groups": Group.objects.prefetch_related('permissions').all(),
    }
    return render(request, 'shopapp/groups-list.html', context=context)


class ProductsListView(ListView):
    template_name = 'shopapp/products-list.html'
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)


class ProductDetailsView(DetailView):
    template_name = 'shopapp/product-details.html'
    model = Product
    context_object_name = 'product'


# class ProductCreateView(UserPassesTestMixin, CreateView):
class ProductCreateView(CreateView):
    # def test_func(self):
    #     # return self.request.user.groups.filter(name='secret-group').exists()
    #     return self.request.user.is_superuser

    model = Product
    fields = 'name', 'price', 'description', 'discount'
    success_url = reverse_lazy('shopapp:products_list')


class ProductUpdateView(UpdateView):
    model = Product
    fields = 'name', 'price', 'description', 'discount'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopapp:product_details',
            kwargs={'pk': self.object.pk}
        )


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
        .select_related('user')
        .prefetch_related('products')
    )
    context_object_name = 'orders'


class OrderDetailsView(PermissionRequiredMixin, DetailView):
    permission_required = 'shopapp.view_order'
    queryset = (
        Order.objects
        .select_related('user')
        .prefetch_related('products')
    )


class OrderCreateView(CreateView):
    model = Order
    # fields = '__all__'
    fields = 'delivery_address', 'promocode', 'user', 'products'
    success_url = reverse_lazy('shopapp:orders_list')


class OrderUpdateView(UpdateView):
    model = Order
    fields = '__all__'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopapp:order_details',
            kwargs={'pk': self.object.pk}
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('shopapp:orders_list')


class ProductsExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by('pk').all()
        products_data = [
            {
                'pk': product.pk,
                'name': product.name,
                'price': product.price,
                'archived': product.archived,
            }
            for product in products
        ]
        return JsonResponse({'products': products_data})


class OrdersExportView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest) -> JsonResponse:
        # orders = Order.objects.select_related('user').prefetch_related('products')
        orders = Order.objects.order_by('pk').all()
        orders_data = [
            {
                'pk': order.pk,
                'delivery_address': order.delivery_address,
                'promocode': order.promocode,
                'user': order.user.pk,
                # 'products': [product for product in order.products.get()],
                'products': [product.pk for product in order.products.all()]
            }
            for order in orders
        ]
        return JsonResponse({'orders': orders_data})

M_10_Testing/mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

<div>
    {% if user.is_authenticated %}
        <div>
            <a href="{% url "myauth:about-me" %}">About me</a> <b>|</b> <a href="{% url "myauth:logout" %}">Logout</a>
            <br>
            <div>
                <a href="{% url 'shopapp:orders_list' %}">Orders list</a> <b>|</b>
                <a href="{% url 'shopapp:products_list' %}">Products list</a>
            </div>
            <div>
                <a href="{% url 'shopapp:products-export' %}">Products JSON</a> <b>|</b>
                <a href="{% url 'shopapp:orders-export' %}">Orders JSON</a>
            </div>
        </div>
    {% else %}
        <div>
            <a href="{% url "myauth:login" %}">Login</a> <b>|</b> <a href="{% url "myauth:register" %}">Register</a>
        <div>
    {% endif %}
</div>

</body>
</html>

M_10_Testing/mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Groups List
{% endblock %}

{% block body %}
  <h1>Groups:</h1>
  <div>
  {% if not groups %}
    <h3>No groups yet</h3>
  {% else %}
    <ul>

      {% for group in groups %}
          <li>
            <div>{{ group.name }}</div>
            <ul>
              {% for permission in group.permissions.all %}
                <li>
                  {{ permission.name }}
                  (<code>{{ permission.codename }}</code>)
                </li>
              {% endfor %}

            </ul>
          </li>
      {% endfor %}

    </ul>
  {% endif %}
  </div>
{% endblock %}

M_10_Testing/mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm delete order #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want delete order #{{ object.pk }}</h1>
  <br>
    <div>
      <a href="{% url 'shopapp:order_details' pk=object.pk %}">
        Back to the order
      </a>
    </div>
  <br>
    <div>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Delete
        </button>
      </form>
    </div>
{% endblock %}

M_10_Testing/mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Order #{{ object.pk }}</h1>
  <div>
    <p>Order by {% firstof object.user.first_name order.user.username %}</p>
    <p>Promoode: <code>{{ object.promocode }}</code></p>
    <p>Delivery address: {{ object.delivery_address }}</p>
    <div>
      Product in order:

      <ul>
        {% for product in object.products.all %}
          <li>{{ product.name }} for ${{ product.price }}</li>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div>
    <a href="{% url 'shopapp:orders_list' %}">
      Back to orders
    </a>
  </div>
  <div>
    <a href="{% url 'shopapp:order_update' pk=object.pk %}">
      Update orders
    </a>
  </div>
  <div>
    <a href="{% url 'shopapp:order_delete' pk=object.pk %}">
      Delete orders
    </a>
  </div>
{% endblock %}

M_10_Testing/mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create order
{% endblock %}

{% block body %}
  <h1>Create a new order</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">
        Create
      </button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:orders_list' %}">
      Back to orders list
    </a>
  </div>
{% endblock %}

M_10_Testing/mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if orders %}
    <div>
      {% for order in orders %}
        <div>
          <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details #{{ order.pk }}</a> </p>
          <p>Order by {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ order.promocode }}</code></p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <div>
            Product in order:
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}

            </ul>
          </div>

        </div>
      {% endfor %}

    </div>
  {% else %}
    <h3>No orders yet</h3>
  {% endif %}

  <div>
    <a href="{% url 'shopapp:order_create'%}">
      Create a new order
    </a>
  </div>
{% endblock %}

M_10_Testing/mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html}

{% block title %}
  Create order
{% endblock %}

{% block body %}
  <h1>Create a new order</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">
        Create
      </button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:orders_list' %}">
      Back to orders list
    </a>
  </div>
{% endblock %}

M_10_Testing/mysite/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Description: <em>{{ product.description }}</em></div>
        <div>Price: {{ product.price }}</div>
        <div>Discount: {{ product.discount }}</div>
        <div>Archived: {{ product.archived }}</div>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Back to products list
        </a>
    </div>

    <div>
        <a href="{% url 'shopapp:product_update' pk=product.pk %}">
            Update product
        </a>
    </div>

    <div>
        <a href="{% url 'shopapp:product_delete' pk=product.pk %}">
            Archived product
        </a>
    </div>

{% endblock %}

M_10_Testing/mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm Archive {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want archive {{ object.name }}</h1>
  <br>
    <div>
      <a href="{% url 'shopapp:product_details' pk=object.pk %}">
        Back to the product
      </a>
    </div>
  <br>
    <div>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Archive
        </button>
      </form>
    </div>
{% endblock %}

M_10_Testing/mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create a new product</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
      <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
  </div>
{% endblock %}

M_10_Testing/mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update product
{% endblock %}

{% block body %}
  <h1>Update a product</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
  <div>
      <a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to products list</a>
  </div>
{% endblock %}

M_10_Testing/mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Products list
{% endblock %}

{% block body %}
  <h1>Products:</h1>
  {% if products %}
    <div>
    {% for product in products %}
      <div>
        <p>
          <a href="{% url 'shopapp:product_details' pk=product.pk %}">Name: {{ product.name }}</a></p>
        <p>Price: {{ product.price }}</p>
        <p>Discount: {% firstof product.discount 'no discount' %}</p>
      </div>
    {% endfor %}

    </div>

  {% else %}
    <h3>No products yet</h3>
  {% endif %}

  <div>
    <a href="{% url 'shopapp:product_create' %}">Create a new product</a>
  </div>
{% endblock %}

M_10_Testing/mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Shop Index
{% endblock %}


{% block body %}
  <h1>Hello Shop Index!</h1>

  <div>
    <ul>
      {% for name, price in products %}
        <li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
        {% if name|length_is:'7' %}
          <span>Lucky product!</span>
        {% endif %}
      {% empty %}
        No products here
      {% endfor %}

    </ul>
  </div>

  <div>
    Time running: {{ time_running }}
  </div>

  <div>
    {% lorem 3 p random %}
  </div>

{% endblock %}